---
- name: Dirty testing of sudoers config
  hosts: all
  gather_facts: false
  vars:
    the_folder: "/etc/sudoers.d/"

  tasks:
    - name: Test some debug stuff
      ansible.builtin.debug:
        msg: "{{ ansible_user }}  {{ ansible_password }}  {{ become_user | default('Not set0') }}  {{ become_password | default('Not set1') }} {{ ssh_password | default('Not set2') }} {{ escalation_password | default('Not set3') }}"

    - name: YADS
      ansible.builtin.debug:
        var: ansible_facts

    - name: Find the contents
      ansible.builtin.find:
        paths: "{{ the_folder }}"
        file_type: file
      register: paths_with_find
      become: true
      become_user: dummy

    - name: Debug the first way
      ansible.builtin.debug:
        var: paths_with_find

    - name: Do you even sudo, bro
      ansible.builtin.command:
        cmd: "sudo -l"
      register: the_sudo_deets
      become: true
      become_user: dummy

    - name: Debug the sudo way
      ansible.builtin.debug:
        var: the_sudo_deets

    - name: Find them the bad way
      ansible.builtin.command:
        cmd: "sudo -l; /usr/bin/ls -al {{ the_folder }}"
      register: paths_with_ls
      become: true
      become_user: dummy


    - name: Debug the second way
      ansible.builtin.debug:
        var: paths_with_ls
