---
- name: Dirty testing of sudoers config
  hosts: all
  vars:
    the_folder: "/etc/sudoers.d/"

  tasks:
    - name: Test some debug stuff
      ansible.builtin.debug:
        msg: "{{ ansible_user }}  {{ ansible_password }}  {{ ansible_become_user }}  {{ ansible_become_password }}"

    - name: Find the contents
      ansible.builtin.find:
        paths: "{{ the_folder }}"
        file_type: file
      register: paths_with_find
      become: true
      become_user: dummy

    - name: Debug the first way
      ansible.builtin.debug:
        var: paths_with_find

    - name: Do you even sudo, bro
      ansible.builtin.command:
        cmd: "sudo -l"
      register: the_sudo_deets
      become: true
      become_user: dummy

    - name: Debug the sudo way
      ansible.builtin.debug:
        var: the_sudo_deets

    - name: Find them the bad way
      ansible.builtin.command:
        cmd: "sudo -l; /usr/bin/ls -al {{ the_folder }}"
      register: paths_with_ls
      become: true
      become_user: dummy

    - name: Debug the second way
      ansible.builtin.debug:
        var: paths_with_ls
