---
aap_organizations:
  - name: "aap"
    description: "Automation Platform Organization"
    state: present

  - name: "midrange"
    description: "Midrange Organization"
    state: present

aap_teams:
  - name: "aix"
    description: "AIX Team"
    organization: "midrange"
    state: present

  - name: "linux"
    description: "Linux Team"
    organization: "midrange"
    state: present

  - name: "windows"
    description: "Windows Team"
    organization: "midrange"
    state: present
    
controller_projects:
  - name: "eda-teams"
    description: "EDA Multiteam Demo"
    organization: "aap"
    scm_type: git
    scm_url: "https://github.com/derekwaters/ansible_devops_demo"
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: true
    update_project: true
    wait: true
    state: present

controller_templates:
  - name: "aix-details"
    playbook: "demo_multi_eda/playbooks/aix-events.yaml"
    job_type: "run"
    organization: "midrange"
    inventory: "Demo Inventory"
    project: "eda-teams"
    ask_variables_on_launch: true
    credentials:
      - "Demo Credential"
    state: present

  - name: "windows-details"
    playbook: "demo_multi_eda/playbooks/windows-events.yaml"
    job_type: "run"
    organization: "midrange"
    inventory: "Demo Inventory"
    project: "eda-teams"
    ask_variables_on_launch: true
    credentials:
      - "Demo Credential"
    state: present

  - name: "linux-details"
    playbook: "demo_multi_eda/playbooks/linux-events.yaml"
    job_type: "run"
    organization: "midrange"
    inventory: "Demo Inventory"
    project: "eda-teams"
    ask_variables_on_launch: true
    credentials:
      - "Demo Credential"
    state: present
...
