---
eda_projects:
  - name: eda_multi
    description: EDA Multiteam Demo
    url: https://github.com/derekwaters/ansible_devops_demo
eda_decision_environments:
  - name: eda_multi_de
    description: EDA Multiteam Demo
    image_url: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8"

eda_user_tokens:
  - name: aap_token
    description: Default AAP Access Token
    token: "{{ awx_token }}"


    
eda_rulebook_activations:
  - name: aix_events
    description: EDA Multiteam Demo - AIX
    project: eda_multi
    rulebook: eda_multiteam_kafka_aix.yml
    decision_environment: eda_multi_de
    awx_token: "aap_token"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present

  - name: windows_events
    description: EDA Multiteam Demo - Windows
    project: eda_multi
    rulebook: eda_multiteam_kafka_windows.yml
    decision_environment: eda_multi_de
    awx_token: "aap_token"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present

  - name: linux_events
    description: EDA Multiteam Demo - Linux
    project: eda_multi
    rulebook: eda_multiteam_kafka_linux.yml
    decision_environment: eda_multi_de
    awx_token: "aap_token"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present