---
eda_projects:
  - name: eda_multi
    description: EDA Multiteam Demo
    organization: aap
    url: https://github.com/derekwaters/ansible_devops_demo
eda_decision_environments:
  - name: eda_multi_de
    description: EDA Multiteam Demo
    organization: aap
    image_url: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8"

eda_credentials:
  - name: aap_access
    description: aap_access
    credential_type: "Red Hat Ansible Automation Platform"
    organization: aap
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"

eda_rulebook_activations:
  - name: aix_events
    description: EDA Multiteam Demo - AIX
    project: eda_multi
    rulebook: eda_multiteam_kafka_aix.yml
    decision_environment: eda_multi_de
    eda_credentials:
      - "aap_access"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present

  - name: windows_events
    description: EDA Multiteam Demo - Windows
    project: eda_multi
    rulebook: eda_multiteam_kafka_windows.yml
    decision_environment: eda_multi_de
    eda_credentials:
      - "aap_access"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present

  - name: linux_events
    description: EDA Multiteam Demo - Linux
    project: eda_multi
    rulebook: eda_multiteam_kafka_linux.yml
    decision_environment: eda_multi_de
    eda_credentials:
      - "aap_access"
    extra_vars:
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
    restart_policy: always
    is_enabled: True
    state: present