---
# OCP Connection Information
ocp_host: openshift.localdomain
ocp_username: admin
ocp_password: password
kafka_namespace: "amqstreams"
kafka_instance_name: "kafka-demo"
kafka_topic_list:
  - "topic1"
  - "topic2"
