# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t ee_builder:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/ee_builder localhost:5000/ee_builder
# * Push the image:
#     podman push localhost:5000/ee_builderee
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.16.5-2"

dependencies:
  system:
    - fuse-overlayfs
  python:
    - ansible-builder
  galaxy: requirements.yml

additional_build_files:
  - src: files/containers.conf
    dest: configs
  - src: files/root_containers.conf
    dest: configs
  - src: files/storage.conf
    dest: configs

additional_build_steps:
  prepend_final:
    - RUN useradd podman;
    - RUN echo podman:10000:5000 > /etc/subuid;
    - RUN echo podman:10000:5000 > /etc/subgid;
    - RUN echo root:20000:5000 >> /etc/subuid;
    - RUN echo root:20000:5000 >> /etc/subgid;
    - COPY _build/configs/containers.conf /home/podman/.config/containers/containers.conf
    - COPY _build/configs/root_containers.conf /etc/containers/containers.conf
    - RUN mkdir -p /home/podman/.local/share/containers
    - RUN mkdir -p /runner/libpod/tmp
    - RUN chown podman:podman -R /home/podman
    - COPY _build/configs/storage.conf /etc/containers/storage.conf
    - RUN sed -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /etc/containers/storage.conf
    - RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock
    - VOLUME /home/podman/.local/share/containers
    - VOLUME /var/lib/containers
    - ENV _CONTAINERS_USERNS_CONFIGURED=""
    - ENV BUILDAH_ISOLATION=chroot

options:
  package_manager_path: /usr/bin/microdnf
