# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t ee_builder:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/ee_builder localhost:5000/ee_builder
# * Push the image:
#     podman push localhost:5000/ee_builderee
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16.5-1"

dependencies:
  python:
    - ansible-builder
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf
