---
controller_hosts:
  - name: "test-host"
    description: "Local Host for Inventory"
    inventory: "platform-inventory"
    state: present
    enabled: true
    variables:
      ansible_connection: local
...