---
controller_hosts:
  - name: "test-host-a"
    description: "Local Host for Inventory"
    inventory: "platform-inventory"
    state: present
    enabled: true
    variables:
      ansible_connection: local
  - name: "test-host-b"
    description: "Local Host for Inventory"
    inventory: "platform-inventory"
    state: present
    enabled: true
    variables:
      ansible_connection: local
  - name: "test-host-c"
    description: "Local Host for Inventory"
    inventory: "platform-inventory"
    state: present
    enabled: true
    variables:
      ansible_connection: local
...