---
- name: Add the new VM to the CMDB inventory in ServiceNow
  hosts: all
  gather_facts: false
  # The following vars should be set on the job
  # snow_instance - the URL to a ServiceNow instance (eg. https://dev123456.service-now.com)
  # snow_username - the ServiceNow API access username
  # snow_password - the ServiceNow API access password
  # ocp_host - the hostname of the openShift API server
  # ocp_token - API Access Token
  tasks:
    - name: Set the VM hostname and namespace vars
      ansible.builtin.set_fact:
        vm_hostname: "{{ ansible_eda.event.body.kubernetes.labels.vm_kubevirt_io_name }}"
        vm_namespace: "{{ ansible_eda.event.body.kubernetes.namespace_name }}"

    - name: Debug 1
      ansible.builtin.debug:
        var: ocp_host
    - name: Debug 2
      ansible.builtin.debug:
        var: ocp_token
    - name: Debug 4
      ansible.builtin.debug:
        var: vm_hostname
    - name: Debug 5
      ansible.builtin.debug:
        var: vm_namespace

    - name: Get VM details from OpenShift Virtualization
      redhat.openshift_virtualization.kubevirt_vm_info:
        host: "{{ ocp_host }}"
        api_key: "{{ ocp_token }}"
        validate_certs: false
        name: "{{ vm_hostname }}"
        namespace: "{{ vm_namespace }}"
      register: vm_details

    - name: Debug the VM details
      ansible.builtin.debug:
        var: vm_details


    - name: Create a configuration item
      servicenow.itsm.configuration_item:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        name: "{{ vm_hostname }}"
        sys_class_name: cmdb_ci_server
        environment: production
        category: Virtual Machine
        other:
          namespace: "{{ vm_namespace }}"
      register: new_ci

    - name: Debug the new CI details
      ansible.builtin.debug:
        var: new_ci
