---
- name: Add a newly created OpenShift Virtualization virtual machine to an AAP Inventory
  hosts: localhost
  gather_facts: false
  vars:
    controller_hosts:
      name: "{{ hostname }}"
      description: "OCPVirt VM {{ hostname }}"
      inventory: "ocpvirt-vms"
      state: present
      enabled: true
  collections:
    - ansible.ansible
  roles:
    - {role: infra.controller_configuration.hosts, when: controller_hosts is defined}
