---
eda_projects:
  - name: acs_kafka_demo
    description: ACS Kafka Broker Demo
    organization: midrange
    url: https://github.com/derekwaters/ansible_devops_demo
eda_decision_environments:
  - name: acs_kafka_demo_de
    description: ACS Kafka Broker Demo
    organization: midrange
    image_url: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8"
eda_credentials:
  - name: aap_access
    description: aap_access
    credential_type: "Red Hat Ansible Automation Platform"
    organization: midrange
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"
eda_rulebook_activations:
  - name: acs_kafka_demo_listener
    description: ACS Kafka Broker Demo
    project: acs_kafka_demo
    rulebook: kafka_trigger_job.yml
    decision_environment: acs_kafka_demo_de
    organization: midrange
    eda_credentials: 
      - "aap_access"
    extra_vars:
      kafkatopic: "{{ kafkatopic | default('eda-topic') }}"
      kafkahostname: "{{ kafkahostname }}"
      kafkaport: "{{ kafkaport | default(9092) }}"
      kafkagroupid: "{{ kafkagroupid | default('eda_group') }}"
      aapjobtemplatename: "acs-kafka-remediate"
    restart_policy: always
    is_enabled: True
    state: present