---
- name: Test EDA Trigger of AIX Events
  hosts: all

  tasks:
    - name: Clarify event type
      ansible.builtin.debug:
        msg: "AIX Event triggered automation"

    - name: Debug AIX Event details
      ansible.builtin.debug:
        var: ansible_eda.event
