---
- name: Test EDA Trigger of Linux Events
  hosts: all

  tasks:
    - name: Clarify event type
      ansible.builtin.debug:
        msg: "Linux Event triggered automation"

    - name: Debug Linux Event details
      ansible.builtin.debug:
        var: ansible_eda.event
