---
- name: Test EDA Trigger of Windows Events
  hosts: all

  tasks:
    - name: Clarify event type
      ansible.builtin.debug:
        msg: "Windows Event triggered automation"

    - name: Debug Windows Event details
      ansible.builtin.debug:
        var: ansible_eda.event
