---
controller_hosts:
  - name: "{{ managed_host }}"
    description: "Local Host for Inventory"
    inventory: "zone-b-assets"
    state: present
    enabled: true
    variables:
      ansible_connection: local
...