---
- name: Include organization role
  ansible.builtin.include_role:
    name: infra.controller_configuration.organizations
  vars:
    assign_galaxy_credentials_to_org: false
    assign_default_ee_to_org: false
  when: controller_organizations | length is not match('0')

- name: Include users role
  ansible.builtin.include_role:
    name: infra.controller_configuration.users
  vars:
    controller_configuration_users_secure_logging: true
  when: controller_user_accounts | length is not match('0')

- name: Include teams role
  ansible.builtin.include_role:
    name: infra.controller_configuration.teams
  when: controller_teams | length is not match('0')

- name: Include credential role
  ansible.builtin.include_role:
    name: infra.controller_configuration.credentials
  vars:
    controller_configuration_credentials_secure_logging: true
  when: controller_credentials | length is not match('0')

- name: Include projects role
  ansible.builtin.include_role:
    name: infra.controller_configuration.projects
  when: controller_projects | length is not match('0')

- name: Include inventories role
  ansible.builtin.include_role:
    name: infra.controller_configuration.inventories
  when: controller_inventories | length is not match('0')

- name: Include hosts role
  ansible.builtin.include_role:
    name: infra.controller_configuration.hosts
  when: controller_hosts | length is not match('0')

- name: Include applications role
  ansible.builtin.include_role:
    name: infra.controller_configuration.applications
  when: controller_applications | length is not match('0')

- name: Include job_templates role
  ansible.builtin.include_role:
    name: infra.controller_configuration.job_templates
  when: controller_templates | length is not match('0')

- name: Include workflow_job_templates role
  ansible.builtin.include_role:
    name: infra.controller_configuration.workflow_job_templates
  when: controller_workflows | length is not match('0')

- name: Include roles role
  ansible.builtin.include_role:
    name: infra.controller_configuration.roles
  when: controller_roles | length is not match('0')

# Deploy EDA Configuration

- name: Include EDA tokens role
  ansible.builtin.include_role:
    name: infra.eda_configuration.user_token
  when: eda_user_tokens | length is not match('0')

- name: Include EDA credentials role
  ansible.builtin.include_role:
    name: infra.eda_configuration.credential
  when: eda_credentials | length is not match('0')

- name: Include EDA projects role
  ansible.builtin.include_role:
    name: infra.eda_configuration.project
  when: eda_projects | length is not match('0')

- name: Include EDA decision environments role
  ansible.builtin.include_role:
    name: infra.eda_configuration.decision_environment
  when: eda_decision_environments | length is not match('0')

- name: Include EDA activations role
  ansible.builtin.include_role:
    name: infra.eda_configuration.rulebook_activation
  when: eda_rulebook_activations | length is not match('0')
...