---
- name: Include organization role
  ansible.builtin.include_role:
    name: infra.controller_configuration.organizations
  vars:
    assign_galaxy_credentials_to_org: false
    assign_default_ee_to_org: false
  when: controller_organizations is defined

- name: Include users role
  ansible.builtin.include_role:
    name: infra.controller_configuration.users
  vars:
    controller_configuration_users_secure_logging: true
  when: controller_user_accounts is defined

- name: Include teams role
  ansible.builtin.include_role:
    name: infra.controller_configuration.teams
  when: controller_teams is defined

- name: Include credential role
  ansible.builtin.include_role:
    name: infra.controller_configuration.credentials
  vars:
    controller_configuration_credentials_secure_logging: true
  when: controller_credentials is defined

- name: Include projects role
  ansible.builtin.include_role:
    name: infra.controller_configuration.projects
  when: controller_projects is defined

- name: Include inventories role
  ansible.builtin.include_role:
    name: infra.controller_configuration.inventories
  when: controller_inventories is defined

- name: Include hosts role
  ansible.builtin.include_role:
    name: infra.controller_configuration.hosts
  when: controller_hosts is defined

- name: Include applications role
  ansible.builtin.include_role:
    name: infra.controller_configuration.applications
  when: controller_applications is defined

- name: Include job_templates role
  ansible.builtin.include_role:
    name: infra.controller_configuration.job_templates
  when: controller_templates is defined

- name: Include workflow_job_templates role
  ansible.builtin.include_role:
    name: infra.controller_configuration.workflow_job_templates
  when: controller_workflows is defined

- name: Include roles role
  ansible.builtin.include_role:
    name: infra.controller_configuration.roles
  when: controller_roles is defined

# Deploy EDA Configuration

- name: Include EDA tokens role
  ansible.builtin.include_role:
    name: infra.eda_configuration.user_token
  when: eda_user_tokens is defined

- name: Include EDA credentials role
  ansible.builtin.include_role:
    name: infra.eda_configuration.credential
  when: eda_credentials is defined

- name: Include EDA projects role
  ansible.builtin.include_role:
    name: infra.eda_configuration.project
  when: eda_projects is defined

- name: Include EDA decision environments role
  ansible.builtin.include_role:
    name: infra.eda_configuration.decision_environment
  when: eda_decision_environments is defined

- name: Include EDA activations role
  ansible.builtin.include_role:
    name: infra.eda_configuration.rulebook_activation
  when: eda_rulebook_activations is defined
...