---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocpvirt-inventory-service-account
  namespace: aap-exec
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-ocpvirt-inventory-serviceaccount
subjects:
  - kind: ServiceAccount
    name: ocpvirt-inventory-service-account
    namespace: aap-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin