---
- name: Launch the demo workflow
  hosts: localhost
# NOTE: This is needed because EDA currently does not support
# launching a workflow job template as an action (only job
# templates).

  tasks:
    - name: Show me all the things
      ansible.builtin.debug:
        var: ansible_facts
    - name: Launch demo implementation workflow
      ansible.controller.workflow_launch:
        workflow_template: "rollout-app-impl"
        wait: false
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
