kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: mcp
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mcp-server-aap
  namespace: mcp
data:
  AAP_PROJECT_ID: '8'
  AAP_TOKEN: $(AAP_TOKEN)
  AAP_URL: $(AAP_URL)
  AAP_VERIFY_SSL: 'false'

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mcp-server-aap
  namespace: mcp
  labels:
    app: mcp-server-aap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-aap
  template:
    metadata:
      name: mcp-server-aap
      labels:
        app: mcp-server-aap
    spec:
      containers:
        - name: mcp-server-aap
          image: 'quay.io/rh-ee-dwaters/mcp-server-aap:latest'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mcp-server-aap

---
kind: Service
apiVersion: v1
metadata:
  name: mcp-server-aap
  namespace: mcp
  labels:
    app: mcp-server-aap
spec:
  type: NodePort
  selector:
    app: mcp-server-aap
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-mcp-server-aap
  namespace: mcp
spec:
  path: /
  to:
    kind: Service
    name: mcp-server-aap
    weight: 100
  host: ''
  port:
    targetPort: http
  alternateBackends: []