# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t ee_kubevirt:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/ee_kubevirt localhost:5000/ee_kubevirt
# * Push the image:
#     podman push localhost:5000/ee_kubevirt
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest"

dependencies:
  galaxy:
    collections:
      - "https://github.com/kubevirt/kubevirt.core/releases/download/2.0.0/kubevirt-core-2.0.0.tar.gz"

options:
  package_manager_path: /usr/bin/microdnf
