---
- name: Listen for events from the AAP activity stream
  hosts: all
  sources:
    - name: Listen to default webhook messages on port 5001
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Empty Organization detected
      condition: >
        event.payload.operation == "create" and
        event.payload.object1 == "credential" and
        event.payload.changes.organization == null
      action:
        run_job_template:
          organization: "midrange"
          name: "remediate-missing-org"
# NOTE: This is commented out as it results in a lot of debug
# in your activation log. But it can give you the full details
# of the event structure being sent
#    - name: Default debug
#      condition: event.payload is defined
#      actions:
#        - debug:
#            var: event.payload