---
- name: Track Linux events
  hosts: all
  sources:
    - name: Listen to Kafka server broker
      ansible.eda.kafka:
        topic: "linux-events"
        host: "{{ kafkahostname }}"
        port: "{{ kafkaport }}"
        group_id: "{{ kafkagroupid }}"
        # Note that the following lines are insecure and should
        # not be used in a production environment
        check_hostname: false
        verify_mode: CERT_OPTIONAL
  rules:
    - name: Trigger Linux jobs
      condition: event.body.host.os_family == "linux" and event.body.severity == "critical"
      actions:
        - run_job_template:
            name: "linux-details"
            organization: midrange
