---
- name: Run a defined job template for creation of new OCPVirt VMs
  hosts: all
  sources:
    - name: Listen to Kubernetes events
      sabre1041.eda.k8s:
        api_version: v1
        kind: VirtualMachine
        #host: "{{ ocp_host }}"
        #api_key: "{{ ocp_apikey }}"
        #verify_ssl: False
  rules:
    - name: New VM
      condition: event.type == "ADDED"
      actions:
        - run_workflow_template:
            name: "add-vm-and-patch"
            organization: "virtualization"
