---
- name: Build the ee_aws image (use the ee_builder EE to do so)
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  collections:
    - infra.ee_utilities
  vars:
    ee_builder_dir_clean: false
    ee_builder_dir: "/tmp/"
    ee_base_registry_username: rh-ee-dwaters
    ee_base_registry_password: "{{ registrypwd }}"
    ee_base_image: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
    ee_registry_dest: "quay.io/rh-ee-dwaters"
    ee_registry_username: rh-ee-dwaters
    ee_registry_password: "{{ registrypwd }}"
    ee_pull_collections_from_hub: false
    ee_verbosity: 3

    ee_list:
      - name: ee_aws
        images:
          base_image: 
            name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
        alt_name: EE for Management of AWS
        tag: 1.0
        dependencies:
          python:
            - botocore
            - boto3
          galaxy:
            collections:
              - amazon.aws

  tasks:
    - name: WhoonearthamI
      ansible.builtin.debug:
        var: ansible_facts

    - name: Do the builder thingo
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
