---
- name: Build the ee_aws image (use the ee_builder EE to do so)
  hosts: localhost
  gather_facts: false
  collections:
    - infra.ee_utilities
  vars:
    ee_builder_dir_clean: false
    ee_builder_dir: "."
    ee_update_base_images: false
    ee_base_image: "quay.io/rh-ee-dwaters/ee-dwaters:latest"
    ee_registry_dest: TBD
    ee_list:
      - name: ee_aws
        alt_name: EE for Management of AWS
        tag: 1.0
        dependencies:
          python:
            - botocore
            - boto3
          galaxy:
            collections:
              - amazon.aws
  roles:
    - infra.ee_utilities.ee_builder