---
- name: Build the ee_aws image (use the ee_builder EE to do so)
  hosts: localhost
  gather_facts: false
  collections:
    - infra.ee_utilities
  vars:
    ee_builder_dir_clean: false
    ee_builder_dir: "."
    ee_base_image: quay.io/rh-ee-dwaters/ee-dwaters-x86:latest
    ee_registry_dest: "quay.io/rh-ee-dwaters"
    ee_registry_username: rh-ee-dwaters
    ee_registry_password: "{{ registrypwd }}"
    ee_verbosity: 3

    ee_list:
      - name: ee_auto_aws
        images:
          base_image: 
            name: quay.io/rh-ee-dwaters/ee-dwaters-x86:latest
        alt_name: EE for Management of AWS
        tag: 1.0
        dependencies:
          python:
            - botocore
            - boto3
          galaxy:
            collections:
              - amazon.aws
  roles:
    - infra.ee_utilities.ee_builder