---
- name: Setup Demo Environment
  hosts: all

  tasks:

    - name: Install AAP and EDA
      ansible.builtin.include_role:
        name: "install_aap_and_eda"

    # Details on how to get a subscription manifest to license AAP can be found here:
    # https://docs.ansible.com/automation-controller/4.4/html/userguide/import_license.html#obtain-sub-manifest
    #
    - name: License AAP
      ansible.controller.license:
        manifest: "{{ aap_manifest_path }}"
        state: present
        tower_host: "{{ aap_host }}"
        tower_username: "{{ aap_username }}"
        tower_password: "{{ aap_password }}"

    - name: Perform the actual demo deployment
      ansible.builtin.include_role:
        name: "deploy_demo"

    - name: Display admin password for AAP
      ansible.builtin.debug:
        msg: "AAP Host is: {{ aap_host }} and Admin password is: '{{ aap_password }}'"

    - name: Display admin password for EDA
      ansible.builtin.debug:
        msg: "EDA Host is: {{ eda_host }} and EDA Admin password is: '{{ eda_password }}'"
