---
- name: Setup Demo Environment
  hosts: all
  vars:
    controller_hostname: "https://demo-aap-aap.apps.cluster-2vvh9.2vvh9.sandbox601.opentlc.com"
    controller_username: "admin"
    controller_password: "HNaUg4zLv26q6QF8hENEEk1VQ8M8axZm"
    aap_configuration_secure_logging: False
    
  tasks:
    # Details on how to get a subscription manifest to license AAP can be found here:
    # https://docs.ansible.com/automation-controller/4.4/html/userguide/import_license.html#obtain-sub-manifest
    #
    - name: Just checking
      ansible.builtin.debug:
        msg: "host is {{ controller_hostname }} pwd is {{ controller_password }}"
        
    - name: License AAP
      ansible.controller.license:
        manifest: "{{ aap_manifest_path }}"
        state: present
        tower_host: "{{ controller_hostname }}"
        tower_username: "{{ controller_username }}"
        tower_password: "{{ controller_password }}"
      retries: 10
      delay: 30

    - name: Set variables for the infra controller
      ansible.builtin.set_fact:
        controller_hostname: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        aap_hostname: "{{ controller_hostname }}"
        aap_username: "{{ controller_username }}"
        aap_password: "{{ controller_password }}"

    - name: Load the Kafka demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars/"
        files_matching: "kafka_config.yml"

    - name: Install Kafka if required
      ansible.builtin.include_role:
        name: "install_kafka"
      when: kafka_namespace is defined and kafka_topic_list is defined

    - name: Load the Developer Hub demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars/"
        files_matching: "rhdh_config.yml"

    - name: Install Developer Hub if required
      ansible.builtin.include_role:
        name: "install_rhdh"
      when: rhdh_namespace is defined

    - name: Load the other demo definition files
      ansible.builtin.include_vars:
        dir: "../{{ demo_name | default('demo_devops') }}/vars"
        ignore_files:
          - "kafka_config.yml"
        extensions:
          - 'yml'

    - name: Perform the actual demo deployment
      ansible.builtin.include_role:
        name: "deploy_demo"

    - name: Display admin password for AAP
      ansible.builtin.debug:
        msg: "AAP Host is: {{ controller_hostname }} and Admin password is: '{{ controller_password }}'"

    - name: Display details for Kafka
      ansible.builtin.debug:
        msg: "Kafka Bootstrap Host is: {{ kafkahostname }}:{{ kafkaport }}"
      when: kafkahostname is defined

    - name: Display details for RHDH
      ansible.builtin.debug:
        msg: "Developer Hub Host is: {{ rhdh_hostname }}"
      when: rhdh_hostname is defined 