---
controller_credentials_all:
  - name: "{{ org_platform.name }}-network-access"
    description: "{{ org_platform.description }} Network Access Credential"
    organization: "{{ org_platform.name }}"
    credential_type: Machine
    inputs:
      username: "{{ network_cred_username }}"
      password: "{{ network_cred_password }}"
    state: present
...