---
controller_hosts_all:
  - name: "{{ managed_host }}"
    description: "Local Host for Inventory"
    inventory: "{{ org_platform.name }}-assets"
    state: present
    enabled: true
    variables:
      ansible_connection: local
...