---
controller_templates:
  - name: "1-create-cr"
    playbook: "demo_devops/playbooks/platform/snow_create_cr.yml"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "2-prerollout"
    playbook: "demo_devops/playbooks/appteam/prerollout_check.yml"
    job_type: "run"
    organization: "{{ org_app.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_app.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "I1-incident"
    playbook: "demo_devops/playbooks/platform/snow_create_incident.yml"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "3-provision"
    playbook: "demo_devops/playbooks/platform/provision_infrastructure.yml"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "4-postprovision"
    playbook: "demo_devops/playbooks/appteam/postprovision_configuration.yml"
    job_type: "run"
    organization: "{{ org_app.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_app.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "5-tvt"
    playbook: "demo_devops/playbooks/appteam/postrollout_tvt.yml"
    job_type: "run"
    organization: "{{ org_app.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_app.name }}-demo"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  # Make this a role would be a better plan
  - name: "S-update-cr-status"
    playbook: "demo_devops/playbooks/platform/snow_set_cr_status.yml"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    survey_enabled: yes
    survey_spec:
      name: "cr_details"
      description: "New state details for CR"
      spec:
        - type: text
          question_name: "new CR status"
          question_description: "What is the new CR status?"
          variable: "new_state"
          required: true
          default: "scheduled"
        - type: text
          question_name: "new CR assignment group"
          question_description: "What is the new CR Assignment Group?"
          variable: "assignment_group"
          required: true
          default: "Software"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  - name: "S-update-cr-closed"
    playbook: "demo_devops/playbooks/platform/snow_set_cr_closed.yml"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    survey_enabled: yes
    survey_spec:
      name: "cr_details"
      description: "New state details for CR"
      spec:
        - type: text
          question_name: "new CR status"
          question_description: "What is the new CR status?"
          variable: "new_state"
          required: true
          default: "scheduled"
        - type: text
          question_name: "new CR assignment group"
          question_description: "What is the new CR Assignment Group?"
          variable: "assignment_group"
          required: true
          default: "Software"
        - type: text
          question_name: "close code for CR"
          question_description: "What is the close code for the CR?"
          variable: "close_code"
          required: true
          default: "successful"
        - type: text
          question_name: "close notes for CR"
          question_description: "What are the closure notes for the CR?"
          variable: "close_notes"
          required: true
          default: "Deployment performed successfully"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present

  # Create a job template to launch a workflow template (ugh)
  - name: "rollout-app"
    job_type: "run"
    organization: "{{ org_platform.name }}"
    inventory: "{{ org_platform.name }}-assets"
    project: "{{ org_platform.name }}-demo"
    playbook: "demo_devops/playbooks/platform/launch_workflow.yml"
    extra_vars:
      controller_hostname: "{{ controller_hostname }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
    credentials:
      - "{{ org_platform.name }}-network-access"
    state: present
...