# Make sure you podman login to the Red Hat registry, then:
# ansible-builder build -t de_kafka_certs:latest
# To host locally:
# * run the docker registry:
#     podman run -d -p 5000:5000 --name registry registry:latest
# * Add the docker registry as an insecure registry:
#     vi /etc/containers/registries.conf.d/099-localhost-registry.conf
#     
#       [[registry]]
#       location = "localhost:5000"
#       insecure = true
#
# * Tag the built image:
#     podman image tag localhost/de_kafka_certs localhost:5000/de_kafka_certs
# * Push the image:
#     podman push localhost:5000/de_kafka_certs
# * Verify the image is there:
#     curl -X GET http://localhost:5000/v2/_catalog

version: 3

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-24/de-supported-rhel8:latest"

additional_build_files:
  - src: files/ca.crt
    dest: configs

additional_build_steps:
  prepend_final:
    - COPY _build/configs/ca.crt /runner/certs/ca.crt

options:
  package_manager_path: /usr/bin/microdnf
